name: random_face_generator
description: This app Generates Random Faces which do not actually exist.
publish_to: 'none'
version: 3.0.0+6
environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  download: ^1.0.0
  path_provider: ^2.0.14
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#E0E5EC"
  image: "assets/app_icon.png"
  color_dark: "#292D32"
  image_dark: "assets/app_icon.png"
  android_12:
    color: "#E0E5EC"
    image: "assets/app_icon.png"
    color_dark: "#292D32"
    image_dark: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/